### ISSUE TITLE
Very low end mistaken which should not happen: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by KevinYaoooooo** [hzy3774/AndroidUn7zip#10]
A: art/runtime/thread.cc:1344] Throwing new exception 'no non-static method "Lai/ones/android/ones/utils/e$2$1;.onError(ILjava/lang/String;)V"' with unexpected pending exception: java.lang.NoSuchMethodError: no non-static method "Lai/ones/android/ones/utils/e$2$1;.onStart()V"
A: art/runtime/thread.cc:1344]   at boolean com.hzy.lib7z.Z7Extractor.nExtractAsset(android.content.res.AssetManager, java.lang.String, java.lang.String, com.hzy.lib7z.a, long) (Z7Extractor.java:-2)
A: art/runtime/thread.cc:1344]   at boolean com.hzy.lib7z.Z7Extractor.a(android.content.res.AssetManager, java.lang.String, java.lang.String, com.hzy.lib7z.a) (Z7Extractor.java:38)

**Comment by huzongyao** [comment]
we should not  proguard the callback methods

**Comment by KevinYaoooooo** [comment]
some how it's not recognising my method

**Comment by KevinYaoooooo** [comment]
ok

**Comment by huzongyao** [comment]
may fix this by keep proguard
-keep class com.hzy.lib7z.** { *; }

**Comment by KevinYaoooooo** [comment]
Thanks, fixed

**Comment by KevinYaoooooo** [comment]
I think you should include this ProGuard rule inside your library package, package together and ship to JCenter, which lead the user of this library no need to add this ProGuard rule inside their projects , ultimately, this ProGuard rule stuff won't be a concern to them.
