### ISSUE TITLE
提取压缩包中单个文件

### ISSUE THREAD

**Issue by Android-Mainli** [hzy3774/AndroidUn7zip#20]
想压缩so 所占apk体积   整体打包so文件40多m 包含所有用到的so文件  想用时单独提取某一个

**Comment by Android-Mainli** [comment]
尝试修改遍历文件名时跳过不需要文件,发现没减少多少时间,您这边有思路么

**Comment by huzongyao** [comment]
如果跳过的文件大的话应该会快一点
