### ISSUE TITLE
ndk编译时error: 'AAsset_getLength64' was not declared in this scope

### ISSUE THREAD

**Issue by fanfanxiaozu** [hzy3774/AndroidUn7zip#27]
././un7zip/7zAssetFile.cpp: In function 'WRes InAssetFile_Open(AAssetManager*, CSzAssetFile*, const char*)':
././un7zip/7zAssetFile.cpp:28:41: error: 'AAsset_getLength64' was not declared in this scope
     p->length = AAsset_getLength64(asset);
                                         ^
make: *** [obj/local/armeabi-v7a/objs/un7zip/./un7zip/7zAssetFile.o] Error 1

**Comment by fanfanxiaozu** [comment]
为了改这个错误././un7zip/7zAssetFile.cpp:33:21: error: 'nullptr' was not declared in this scope
修改了LOCAL_CFLAGS += -Wall -ffunction-sections -fdata-sections -std=c++0x
还是编不过

**Comment by huzongyao** [comment]
fixed and please try again
