### ISSUE TITLE
Migrate from JCenter to another maven repository

### ISSUE THREAD

**Issue by andob** [hzy3774/AndroidUn7zip#29]
Are you using JCenter to host the artifact?

Because if I remove jcenter() from repositories gradle block, the library won't be imported:

```
repositories {
        jcenter() //if I remove this
}

dependencies {
        implementation 'com.hzy:un7zip:1.7.1'
}
```

JCenter is at end of life. Please migrate if needed.

**Comment by andob** [comment]
one can import the artifact from JitPack.

```
repositories {
    maven { url 'https://jitpack.io' }
}

dependencies {
   implementation 'com.github.hzy3774:AndroidP7zip:v1.7.2'
}
```

@hzy3774 please update documentation on README.md on how to import the library.

**Comment by huzongyao** [comment]
ok, thank you
